# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - fr-access-admin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish Admin app
        run: |
          dotnet publish Admin/FirstReg.Admin.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"
          if (Test-Path "${{env.DOTNET_ROOT}}/myapp/appsettings.Development.json") {
            Remove-Item "${{env.DOTNET_ROOT}}/myapp/appsettings.Development.json"
          }

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_292D33F44ACA4012B48D804BAD878090 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E314025DDE754C068D9882BED5A071BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A066D1890D2F4E09B11A64FA495BDC6C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fr-access-admin'
          slot-name: 'Production'
          package: .
